version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: library-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: library-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/library?authSource=admin
      - JWT_SECRET=your-secure-production-secret-key
      - JWT_EXPIRES_IN=1h
      - RATE_LIMIT_WINDOW=60000
      - MAX_REQUESTS=60
      - CSRF_SECRET=your-csrf-secret-key
      - AUDIT_LOG_ENABLED=true
      - CORS_ORIGIN=http://localhost:3001
      - CACHE_ENABLED=true
      - CACHE_TTL=300000
    depends_on:
      - mongodb
    networks:
      - library-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - NODE_ENV=production
      - REACT_APP_ENABLE_CACHE=true
      - REACT_APP_CACHE_TTL=300000
      - REACT_APP_ENABLE_CSRF=true
      - REACT_APP_ENABLE_RATE_LIMIT=true
      - REACT_APP_ENABLE_AUDIT_LOG=true
      - REACT_APP_ENABLE_PERFORMANCE_MONITORING=true
    depends_on:
      - backend
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  library-network:
    driver: bridge 