module.exports = {
  "API_URL": "http://localhost:5001",
  "API_TIMEOUT": 10000,
  "ENABLE_RATE_LIMIT": false,
  "RATE_LIMIT_WINDOW": 60000,
  "RATE_LIMIT_MAX_REQUESTS": 100,
  "ENABLE_CSRF": false,
  "CSRF_TOKEN_HEADER": "X-CSRF-Token",
  "ENABLE_AUDIT_LOG": true,
  "AUDIT_LOG_LEVEL": "debug",
  "AUTH_TOKEN_KEY": "test_auth_token",
  "AUTH_REFRESH_TOKEN_KEY": "test_refresh_token",
  "AUTH_TOKEN_EXPIRY": 3600,
  "ENABLE_EXPORT": true,
  "ENABLE_BULK_ACTIONS": true,
  "ENABLE_ADVANCED_FILTERS": true,
  "DEFAULT_PAGE_SIZE": 10,
  "MAX_PAGE_SIZE": 100,
  "SHOW_ERROR_DETAILS": true,
  "ERROR_MESSAGE_DURATION": 5000,
  "DB_HOST": "localhost",
  "DB_PORT": 27018,
  "DB_NAME": "library_test",
  "EMAIL_HOST": "smtp.test.com",
  "EMAIL_PORT": 2525,
  "EMAIL_USER": "test@example.com",
  "EMAIL_PASSWORD": "test_password",
  "MAX_FILE_SIZE": 5242880,
  "ALLOWED_FILE_TYPES": [
    "image/jpeg",
    "image/png",
    "application/pdf"
  ],
  "CACHE_ENABLED": true,
  "CACHE_TTL": 3600,
  "ENABLE_MONITORING": true,
  "MONITORING_INTERVAL": 300000,
  "TEST_MODE": true,
  "TEST_API_KEY": "test-api-key",
  "TEST_USER_ID": "test-user-id",
  "TEST_ADMIN_ID": "test-admin-id",
  "MOCK_API_DELAY": 100,
  "TEST_DATA_DIR": "./test-data"
};